### ISSUE TITLE
Cannot compile documentation

### ISSUE THREAD

**Issue by dolfim** [force-h2020/force-wfmanager#127]
After installing the documentation requirements I run `make html` in the `doc` folder.

The result is:
```
    from pyface.ui.qt4.util.gui_test_assistant import GuiTestAssistant
  File "/Users/dol/.edm/envs/force/lib/python3.5/site-packages/pyface/ui/qt4/util/gui_test_assistant.py", line 13, in <module>
    import mock
ImportError: No module named 'mock'
```

It looks like the version of `pyface` doesn't have Python3 tests. The `mock` module should be included as `from unittest import mock`

**Comment by dolfim** [comment]
It seems I was missing the `pip install -r requirements/dev_requirements.txt`

**Comment by stefanoborini** [comment]
Closing this one as you found the solution.
