### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by corranwebster** [force-h2020/force-wfmanager#130]
In particular, there has been a new release of Chaco, so don't need to compile it (which then removes need for SWIG, Cython, perhaps some others).

**Comment by jjenthought** [comment]
This means we can remove swig and cython from edm_requirements and add chaco (4.7.1). Installing chaco via pip doesn't work without swig/cython, but does work if installed via edm install.

**Comment by stefanoborini** [comment]
Fixed by #159
