### ISSUE TITLE
Use BaseFactory Instances 

### ISSUE THREAD

**Issue by jjenthought** [force-h2020/force-wfmanager#198]
Where there are expressions using Either(Instance(Factory1),Instance(Factory2)) in the code, use Instance(BaseFactory) instead.

**Comment by stefanoborini** [comment]
There are other points where we can do this.

**Comment by stefanoborini** [comment]
I assign it to you but if you are swamped let me know and I can do it.

**Comment by jjenthought** [comment]
I think I tried replacing the remaining ones, selected_factory and in the TreeNode definition iirc? For some reason selected_factory didn't work correctly with BaseFactory, possibly because it has no create_model() method.
It actually was okay to have the TreeNode definition use BaseFactory but since selected factory was still an Either() I didn't want to leave unselectable factories. I.e. a factory that is a BaseFactory but not one of the ones in the Either() list.

**Comment by flongford** [comment]
Closing this since `selected_factory` is no longer defined by an `Either` trait type.
