### ISSUE TITLE
Prevent HTML Editor being prioritised when UI size changes

### ISSUE THREAD

**Issue by jjenthought** [force-h2020/force-wfmanager#217]
For the datasource descriptions, the HTML editor takes up the maximum amount of space it possibly can - at the minute it would make more sense to allocate this space to the input & output tables. 
Unfortunately this currently happens even when the HTML editor is passed a value for height!

**Comment by jjenthought** [comment]
As far as I can tell, the source of this problem is that in Qt the QWebView has a default sizehint of 800x600. This is not a property which can be set as far as I can tell. 
So the widget will always take any extra space until it gets to the sizehint, even under the most conservative sizepolicy setting.
You can set the size via .setmaximumwhatever() in Qt, but that doesn't really help us.

**Comment by stefanoborini** [comment]
I suspect that the only way to work around it is to either contain it in a separate view that is constrained, or that you enforce a sizing policy for all the other members of the group.
