### ISSUE TITLE
Project is pinned to a particular TraitsUI commit

### ISSUE THREAD

**Issue by ml-evs** [force-h2020/force-wfmanager#258]
This should be changed as soon as a new TraitsUI build is released that merges enthought/traitsui#521.

**Comment by flongford** [comment]
This also links to https://github.com/force-h2020/force-wfmanager/pull/278

Using `GuiTaskAssistant` from pyface 6.0.0-2 requires `mock` 3rd party library (which we ideally don't want to use)

Updating to pyface 6.1.0-1, would replace `mock` with `unittest.mock`, though this requires unpinning the current TraitsUI build

**Comment by nicolasap-dm** [comment]
Closed by #288
