### ISSUE TITLE
Target KPI specification only works if user-specified order matches output slots

### ISSUE THREAD

**Issue by ml-evs** [force-h2020/force-wfmanager#259]
As an example, say your DataSource has outputs ['x', 'y', 'z'], and you target the KPIs ['z', 'x', 'y'] by selecting them in the user interface. This will lead to mislabelled KPIs in the analysis, as the workflow manager assumes the first KPI is also the first output slot.

This also follows if the number of slots is greater than the number of requested KPIs. Consider a DataSource that returns ['x', 'y', 'V_xy']. If the user asks for 'V_xy' only, then they shall receive it correctly. If the user asks for ['V_xy', 'y'], then empirically it seems that they receive ['y', 'V_xy'], though interestingly asking for ['x', 'V_xy'] seems to work... I'll investigate and file a PR.

**Comment by ml-evs** [comment]
This could be fixed in a couple of different ways:
1. reordering/stripping out data values as the wfmanager ingests `MCOProgressEvent`s.
2. enforce that MCO's always notify the wfmanager with the correct outputs, by either
    i) adding extra methods to BaseMCO/BaseMCOModel in force_bdss's API that wrap calls to the data source (this would require restructuring existing plugins)
    ii) simply trusting plugin developers to only notify new points in a manner that follows the model's KPISpecification.

I would be in favour of both (1) + (2.i): (1) is a one line fix (see PR #259), but I also think implementing (2.i) makes what is expected of an MCO clearer to plugin developers, as the MCOModel and MCO outputs should be self-consistent.

**Comment by ml-evs** [comment]
This bug has been fixed in the above PR to force-bdss, but we may want to add checks in the wf_manager code that KPIs cannot be specified multiple times (e.g. `[MINIMISE x, MAXIMISE x]` is curretly possible...). We should probably also enforce that at least one KPI is specified, otherwise many plugins crash when trying to set the KPI weights.

**Comment by flongford** [comment]
This issue has been taken care of in #313
