### ISSUE TITLE
Source code directory structure corresponds to old GUI layout

### ISSUE THREAD

**Issue by ml-evs** [force-h2020/force-wfmanager#260]
e.g. source files are stored under left_side_pane or central_pane, for features/views that no longer correspond to that pane. Would be nice if we could tidy this up (and probably group files by feature, rather than GUI layout) to make it easier to contribute.

**Comment by corranwebster** [comment]
Ha! I was just about to come and add this as an issue this morning after starting to seriously read the code.

**Comment by ml-evs** [comment]
Chatted a little bit with @jjenthought about this earlier, here is my proposed layout. All I have done so far is move around the files, so it seems like it is better to discuss this here than in a full PR.

Replace `left_side_pane/` and `central_pane/` with functionality grouped by task, namely `setup/` and `results/`. 

```
$ tree force_wfmanager -L 1
force_wfmanager
├── __init__.py
├── dialogs
├── gui
├── images
├── plugins
├── results
├── server
├── setup
├── tests
├── utils
├── wfmanager.py
├── wfmanager_plugin.py
├── wfmanager_results_task.py
└── wfmanager_setup_task.py
```

These modules could be divided into `models/`, `views/` and `panes/`, as follows:

```
$ tree results
results
├── __init__.py
├── models
│   ├── __init__.py
│   └── analysis_model.py
├── panes
│   ├── __init__.py
│   ├── graph_pane.py
│   └── results_pane.py
├── tests
│   ├── __init__.py
│   ├── test_analysis_model.py
│   ├── test_graph_pane.py
│   ├── test_plot.py
│   ├── test_result_table.py
│   └── test_setup_pane.py
└── views
    ├── __init__.py
    ├── plot.py
    └── result_table.py
```

```
$ tree setup
setup
├── __init__.py
├── models
│   ├── __init__.py
│   ├── new_entity_creator.py
│   ├── tree_pane.py
│   ├── variable_names_registry.py
│   ├── workflow_info.py
│   └── workflow_tree.py
├── panes
│   ├── __init__.py
│   └── setup_pane.py
├── tests
│   ├── __init__.py
│   ├── test_data_source_model_view.py
│   ├── test_factory_name.py
│   ├── test_kpi_specification_model_view.py
│   ├── test_mco_model_view.py
│   ├── test_mco_parameter_model_view.py
│   ├── test_new_entity_creator.py
│   ├── test_notification_listener_model_view.py
│   ├── test_result_pane.py
│   ├── test_variable_names_registry.py
│   ├── test_workflow_info.py
│   ├── test_workflow_model_view.py
│   └── test_workflow_tree.py
└── views
    ├── __init__.py
    ├── data_source_model_view.py
    ├── execution_layer_model_view.py
    ├── kpi_specification_model_view.py
    ├── mco_model_view.py
    ├── mco_parameter_model_view.py
    ├── notification_listener_model_view.py
    ├── view_utils.py
    └── workflow_model_view.py
```

However, some things currently in `setup/models/` are not models, e.g. the `new_entity_creator.py` submodule, and "`views`" probably isn't the right name for e.g. `results/views/plot.py`, and should be replaced by a word to the effect of "something that a pane can display".

There's some other assorted tidying of e.g. a top-level `dialogs/` folder (currently contains the `plugin_dialog`) that may be useful for developing e.g. "quickstart" workflow creators. Some miscellaenous functionality (`local_traits` and `task_toggle_group_accelerator`) have been moved to `utils/`.
