### ISSUE TITLE
Text in "Available Plugins" Listbox is Editable

### ISSUE THREAD

**Issue by corranwebster** [force-h2020/force-wfmanager#261]
They clearly should be read-only.

![Screen Shot 2019-04-01 at 10 32 57 am](https://user-images.githubusercontent.com/600761/55317972-8f0ffe00-5469-11e9-9ecf-32800ec6735e.png)

**Comment by ml-evs** [comment]
Here are the offending lines:

https://github.com/force-h2020/force-wfmanager/blob/a9c048d15c59e608ce6754d3fef6931f5af55737/force_wfmanager/left_side_pane/workflow_info.py#L92-L95

Passing `editable=False` seems to fix things, I'll make a PR that includes other interface changes.
