### ISSUE TITLE
BasePlot: avoid potentially damaging changes of state across threads

### ISSUE THREAD

**Issue by nicolasap-dm** [force-h2020/force-wfmanager#320]
There are a couple of design flaws in `BasePlot`:

1. the plot's own `_data_arrays` are updated `on_trait_change('analysis_model.evaluation_steps[]')` even if the plot gets updated only on the timer's clock. This is non optimal. Also, `update_data_arrays` makes operation using `evaluation_steps` that are changing, which could lead to unexpected errors. We should 
   1. only get the new evaluation_steps when it's needed, i.e. when the timer goes off
   2. make sure that we always ever update the `_data_arrays` using a copy of `analysis.mode.evaluation_steps`, and not a (numpy) view into the original `evaluation_steps` that are being changed by another thread

2. the timer may call a redraw of the plot before Chaco has finished the last operation. This may result in a crash (reproduce by running an MCO with 4000+ evaluation steps and selecting the Example Line Plot from the bdss-plugin-enthought-example). We should make sure that the call to `_update_plot` ends up in the correct thread. Using [`dispatch="ui"`](https://docs.enthought.com/traits/traits_api_reference/has_traits.html#traits.has_traits.HasTraits.on_trait_change) for the notification handlers may be the way to go about this.

**Comment by corranwebster** [comment]
Note here - the timer should be fine.  If the drawing takes more than the interval between "ticks" of the timer, the next timer call will just be delayed until after the drawing has finished.  The timer ticks are a minimum time between calls, not a guarantee.  Any problems you are seeing are because of off-ui-thread changes to ui-thread state (ie. 1)

**Comment by nicolasap-dm** [comment]
№ 1 addressed in #323 

№ 2: it turned out that the crash was caused by a mishandled exception in chaco and qt, and wasn't dependent on the timer https://github.com/enthought/chaco/issues/474 – nothing to fix here
