### ISSUE TITLE
MCOProgressEvent should accept metadata instead of weights

### ISSUE THREAD

**Issue by Corwinpro** [force-h2020/force-wfmanager#333]
The signature of `MCOProgressEvent` is [hard-coded](https://github.com/force-h2020/force-wfmanager/blob/f9ca5b47189b1a23dff3563716e11f0bed345693/force_wfmanager/wfmanager_setup_task.py#L470) into the workflow manager, and therefore it is impossible to change the event behaviour solely on the `force-bdss` level. In particular, whenever this event occurs, the WFManager expects the event to have the `weights` attribute, which may be absent for various reasons.

We can consider two options:
- Refactor `_server_event_mainthread` to parse metadata instead of just weights. This expands the range of possible data we can pass to the workflow manager, but it seems wrong to make `wfmanager_setup_task.py` responsible for this.
-  Implement a serialisation method for `MCOStartEvent`, `MCOProgressEvent` in a way the classes themselves are responsible for the data representation

**Comment by Corwinpro** [comment]
This is also related to [this issue](https://github.com/force-h2020/force-bdss/issues/239)

**Comment by Corwinpro** [comment]
[This BDSS PR](https://github.com/force-h2020/force-bdss/pull/244) introduced major changes to `MCOEvents` initialization. Now it should be easier to approach this issue.

**Comment by flongford** [comment]
I believe this can be closed @Corwinpro? I can create a separate issue for moving the `BaseDriverEvent` serialization and deserialization code onto the classes themselves
