### ISSUE TITLE
Add clear data button in the central pane

### ISSUE THREAD

**Issue by martinRenou** [force-h2020/force-wfmanager#81]
We should add a "Clear" button in the central pane to clear the current analysis model

**Comment by stefanoborini** [comment]
Remember to add a dialog for confirmation. You have it in pyface.
Question is eventually where to put it.
Another question is if you should have a button or a menu entry.

**Comment by stefanoborini** [comment]
Closing. We agreed we don't get anything really out of it, as the data is properly reset at the execution of a new evaluation.
